os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  provider: script
  script:
    - flutter test
  on:
    tags: true
notifications:
  slack:
    secure: y3hcy+ORmjjxIxTWrzkRJ+KdL9DhLJL2dGnzWWrQgwqYucT3v/PQZ9N/0LqXv9ZaBdkblQqa/jk397aab9Qnk2ckM3kFfLbRpserKMTnMYp5DzdxIWn6Ybitf8OxChQGnJXW1JXyLi9Hwy9pdPKQFfTMC52NImX6cles80lbyfjUCycIfE2vFC11u7qcROD1VaetGfHeNGgpGKjO28etlyJweN0iz+W7SrI5K6d8hnb29ObszGBJaAcyAU8IuPCRuwjN0eb1G5PASIREEXxsv+xQhRC/ARl1nNplCF9MV+kF0lbOyjQSoZAxyC2eAAdXhX0jVzI54Oq+a5AlauTAmWI5ltP7TBBFtGqZg7JMbilY3jeuVXKXxk2zLHsoKNpuwwXlwqFHzd6+p5AFP6w4kp15150+hPBKfw662hlQt8STMXuq/YQy/rUrTCjyygOMi7AUseIrpLOEPe2fHom/Rvn/Zifh3xCHxe6SXTYDIM4VoIvzX7KpfKgiNTsPlGfdZwT67t4BfZ+A2YBNvJsm//pSZdf7GgXPv8FcYeZCoApMEraeW07u4mv66xkJRjszt5YexjhosH1EEttkgfwgcJMor4hl/q8tghBxNy8m63pa5Ic+52u4dBGSkmU+6MSQ99ibkAIg+1mbQvf/uOnjzou7ARtFkEK7zodElCY/FhM=